/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as AshaRouteImport } from './routes/asha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ClinicianIndexRouteImport } from './routes/clinician.index'
import { Route as AshaIndexRouteImport } from './routes/asha.index'
import { Route as ParentSpeechRouteImport } from './routes/parent.speech'
import { Route as ParentScreeningRouteImport } from './routes/parent.screening'
import { Route as ParentReferralRouteImport } from './routes/parent.referral'
import { Route as ParentRecommendationsRouteImport } from './routes/parent.recommendations'
import { Route as ParentPassportRouteImport } from './routes/parent.passport'
import { Route as ParentMotorRouteImport } from './routes/parent.motor'
import { Route as ClinicianAnalyticsRouteImport } from './routes/clinician.analytics'
import { Route as AshaRegisterRouteImport } from './routes/asha.register'
import { Route as AshaInsightsRouteImport } from './routes/asha.insights'
import { Route as AshaFollowupRouteImport } from './routes/asha.followup'
import { Route as ClinicianReviewIdRouteImport } from './routes/clinician.review.$id'

const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const AshaRoute = AshaRouteImport.update({
  id: '/asha',
  path: '/asha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ClinicianIndexRoute = ClinicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicianRoute,
} as any)
const AshaIndexRoute = AshaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AshaRoute,
} as any)
const ParentSpeechRoute = ParentSpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => ParentRoute,
} as any)
const ParentScreeningRoute = ParentScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => ParentRoute,
} as any)
const ParentReferralRoute = ParentReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => ParentRoute,
} as any)
const ParentRecommendationsRoute = ParentRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => ParentRoute,
} as any)
const ParentPassportRoute = ParentPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMotorRoute = ParentMotorRouteImport.update({
  id: '/motor',
  path: '/motor',
  getParentRoute: () => ParentRoute,
} as any)
const ClinicianAnalyticsRoute = ClinicianAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ClinicianRoute,
} as any)
const AshaRegisterRoute = AshaRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AshaRoute,
} as any)
const AshaInsightsRoute = AshaInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AshaRoute,
} as any)
const AshaFollowupRoute = AshaFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => AshaRoute,
} as any)
const ClinicianReviewIdRoute = ClinicianReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => ClinicianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asha': typeof AshaRouteWithChildren
  '/clinician': typeof ClinicianRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/asha/followup': typeof AshaFollowupRoute
  '/asha/insights': typeof AshaInsightsRoute
  '/asha/register': typeof AshaRegisterRoute
  '/clinician/analytics': typeof ClinicianAnalyticsRoute
  '/parent/motor': typeof ParentMotorRoute
  '/parent/passport': typeof ParentPassportRoute
  '/parent/recommendations': typeof ParentRecommendationsRoute
  '/parent/referral': typeof ParentReferralRoute
  '/parent/screening': typeof ParentScreeningRoute
  '/parent/speech': typeof ParentSpeechRoute
  '/asha/': typeof AshaIndexRoute
  '/clinician/': typeof ClinicianIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/clinician/review/$id': typeof ClinicianReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asha/followup': typeof AshaFollowupRoute
  '/asha/insights': typeof AshaInsightsRoute
  '/asha/register': typeof AshaRegisterRoute
  '/clinician/analytics': typeof ClinicianAnalyticsRoute
  '/parent/motor': typeof ParentMotorRoute
  '/parent/passport': typeof ParentPassportRoute
  '/parent/recommendations': typeof ParentRecommendationsRoute
  '/parent/referral': typeof ParentReferralRoute
  '/parent/screening': typeof ParentScreeningRoute
  '/parent/speech': typeof ParentSpeechRoute
  '/asha': typeof AshaIndexRoute
  '/clinician': typeof ClinicianIndexRoute
  '/parent': typeof ParentIndexRoute
  '/clinician/review/$id': typeof ClinicianReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asha': typeof AshaRouteWithChildren
  '/clinician': typeof ClinicianRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/asha/followup': typeof AshaFollowupRoute
  '/asha/insights': typeof AshaInsightsRoute
  '/asha/register': typeof AshaRegisterRoute
  '/clinician/analytics': typeof ClinicianAnalyticsRoute
  '/parent/motor': typeof ParentMotorRoute
  '/parent/passport': typeof ParentPassportRoute
  '/parent/recommendations': typeof ParentRecommendationsRoute
  '/parent/referral': typeof ParentReferralRoute
  '/parent/screening': typeof ParentScreeningRoute
  '/parent/speech': typeof ParentSpeechRoute
  '/asha/': typeof AshaIndexRoute
  '/clinician/': typeof ClinicianIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/clinician/review/$id': typeof ClinicianReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asha'
    | '/clinician'
    | '/parent'
    | '/asha/followup'
    | '/asha/insights'
    | '/asha/register'
    | '/clinician/analytics'
    | '/parent/motor'
    | '/parent/passport'
    | '/parent/recommendations'
    | '/parent/referral'
    | '/parent/screening'
    | '/parent/speech'
    | '/asha/'
    | '/clinician/'
    | '/parent/'
    | '/clinician/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asha/followup'
    | '/asha/insights'
    | '/asha/register'
    | '/clinician/analytics'
    | '/parent/motor'
    | '/parent/passport'
    | '/parent/recommendations'
    | '/parent/referral'
    | '/parent/screening'
    | '/parent/speech'
    | '/asha'
    | '/clinician'
    | '/parent'
    | '/clinician/review/$id'
  id:
    | '__root__'
    | '/'
    | '/asha'
    | '/clinician'
    | '/parent'
    | '/asha/followup'
    | '/asha/insights'
    | '/asha/register'
    | '/clinician/analytics'
    | '/parent/motor'
    | '/parent/passport'
    | '/parent/recommendations'
    | '/parent/referral'
    | '/parent/screening'
    | '/parent/speech'
    | '/asha/'
    | '/clinician/'
    | '/parent/'
    | '/clinician/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AshaRoute: typeof AshaRouteWithChildren
  ClinicianRoute: typeof ClinicianRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asha': {
      id: '/asha'
      path: '/asha'
      fullPath: '/asha'
      preLoaderRoute: typeof AshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/clinician/': {
      id: '/clinician/'
      path: '/'
      fullPath: '/clinician/'
      preLoaderRoute: typeof ClinicianIndexRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/asha/': {
      id: '/asha/'
      path: '/'
      fullPath: '/asha/'
      preLoaderRoute: typeof AshaIndexRouteImport
      parentRoute: typeof AshaRoute
    }
    '/parent/speech': {
      id: '/parent/speech'
      path: '/speech'
      fullPath: '/parent/speech'
      preLoaderRoute: typeof ParentSpeechRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/screening': {
      id: '/parent/screening'
      path: '/screening'
      fullPath: '/parent/screening'
      preLoaderRoute: typeof ParentScreeningRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/referral': {
      id: '/parent/referral'
      path: '/referral'
      fullPath: '/parent/referral'
      preLoaderRoute: typeof ParentReferralRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/recommendations': {
      id: '/parent/recommendations'
      path: '/recommendations'
      fullPath: '/parent/recommendations'
      preLoaderRoute: typeof ParentRecommendationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/passport': {
      id: '/parent/passport'
      path: '/passport'
      fullPath: '/parent/passport'
      preLoaderRoute: typeof ParentPassportRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/motor': {
      id: '/parent/motor'
      path: '/motor'
      fullPath: '/parent/motor'
      preLoaderRoute: typeof ParentMotorRouteImport
      parentRoute: typeof ParentRoute
    }
    '/clinician/analytics': {
      id: '/clinician/analytics'
      path: '/analytics'
      fullPath: '/clinician/analytics'
      preLoaderRoute: typeof ClinicianAnalyticsRouteImport
      parentRoute: typeof ClinicianRoute
    }
    '/asha/register': {
      id: '/asha/register'
      path: '/register'
      fullPath: '/asha/register'
      preLoaderRoute: typeof AshaRegisterRouteImport
      parentRoute: typeof AshaRoute
    }
    '/asha/insights': {
      id: '/asha/insights'
      path: '/insights'
      fullPath: '/asha/insights'
      preLoaderRoute: typeof AshaInsightsRouteImport
      parentRoute: typeof AshaRoute
    }
    '/asha/followup': {
      id: '/asha/followup'
      path: '/followup'
      fullPath: '/asha/followup'
      preLoaderRoute: typeof AshaFollowupRouteImport
      parentRoute: typeof AshaRoute
    }
    '/clinician/review/$id': {
      id: '/clinician/review/$id'
      path: '/review/$id'
      fullPath: '/clinician/review/$id'
      preLoaderRoute: typeof ClinicianReviewIdRouteImport
      parentRoute: typeof ClinicianRoute
    }
  }
}

interface AshaRouteChildren {
  AshaFollowupRoute: typeof AshaFollowupRoute
  AshaInsightsRoute: typeof AshaInsightsRoute
  AshaRegisterRoute: typeof AshaRegisterRoute
  AshaIndexRoute: typeof AshaIndexRoute
}

const AshaRouteChildren: AshaRouteChildren = {
  AshaFollowupRoute: AshaFollowupRoute,
  AshaInsightsRoute: AshaInsightsRoute,
  AshaRegisterRoute: AshaRegisterRoute,
  AshaIndexRoute: AshaIndexRoute,
}

const AshaRouteWithChildren = AshaRoute._addFileChildren(AshaRouteChildren)

interface ClinicianRouteChildren {
  ClinicianAnalyticsRoute: typeof ClinicianAnalyticsRoute
  ClinicianIndexRoute: typeof ClinicianIndexRoute
  ClinicianReviewIdRoute: typeof ClinicianReviewIdRoute
}

const ClinicianRouteChildren: ClinicianRouteChildren = {
  ClinicianAnalyticsRoute: ClinicianAnalyticsRoute,
  ClinicianIndexRoute: ClinicianIndexRoute,
  ClinicianReviewIdRoute: ClinicianReviewIdRoute,
}

const ClinicianRouteWithChildren = ClinicianRoute._addFileChildren(
  ClinicianRouteChildren,
)

interface ParentRouteChildren {
  ParentMotorRoute: typeof ParentMotorRoute
  ParentPassportRoute: typeof ParentPassportRoute
  ParentRecommendationsRoute: typeof ParentRecommendationsRoute
  ParentReferralRoute: typeof ParentReferralRoute
  ParentScreeningRoute: typeof ParentScreeningRoute
  ParentSpeechRoute: typeof ParentSpeechRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentMotorRoute: ParentMotorRoute,
  ParentPassportRoute: ParentPassportRoute,
  ParentRecommendationsRoute: ParentRecommendationsRoute,
  ParentReferralRoute: ParentReferralRoute,
  ParentScreeningRoute: ParentScreeningRoute,
  ParentSpeechRoute: ParentSpeechRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AshaRoute: AshaRouteWithChildren,
  ClinicianRoute: ClinicianRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
